extends: airbnb-base
parser: babel-eslint
plugins:
  - jest
  - babel
  - import

env:
  node: true
  es6: true
  jest/globals: true

rules:
  no-use-before-define: 0
  no-await-in-loop: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  import/prefer-default-export: 0
  jest/no-focused-tests: error
  import/named: error
  import/no-unresolved: error
  max-len:
    - error
    - 100
